---
# 把样例项目中的配置文件复制过来替换即可
# 项目的名字
name: Cinic-10分类
# 项目的作者
author: 王庆法
# 项目的描述
description: CINIC-10分类
# 项目使用的网络
algorithm: CNN
language: python3
# 项目使用的框架
framework: Pytorch

# 使用的数据集
data:
  # 数据集id
  # 该id为上传数据生成的id
  # 通过该id下载可以对应的数据集
  id: Cinic-10_V1
  name: Cinic-10分类
  category: image

# 数据模型
model:
  # 数据处理类
  # 通过python的反射，生成该对象
  processor: Processor
  # 输入x数据处理的方法
  # 通过反射调用，可以修改名字
  input_x: input_x
  # 输入y数据处理的方法
  # 通过反射调用，可以修改名字
  input_y: input_y
  # 模型输出y数据处理的方法
  # 通过反射调用，可以修改名字
  output_x: output_x
  # 模型输出y数据处理的方法
  # 通过反射调用，可以修改名字
  output_y: output_y
  # 模型用到的输入x字段
  # 在processor.py的input_x方法中体现
  input:
    columns:
      - name: image_path
        type: url
    # 最终转换的数据类型
    to_type: float
    # 最终转换的数据维度
    to_shape: [-1,28,28,3]
  # 模型用到的输入y字段
  # 在processor.py的input_y方法中体现
  output:
    columns:
      - name: labels
        type: int
    # 最终转换的数据类型
    to_type: int
    # 最终转换的数据维度
    to_shape: [10]

# 使用离线训练的服务器
servers:
 - id: flyai
   url: https://www.flyai.com
...